apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: depl
  name: depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: depl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: depl
    spec:
      containers:
      - image: scinet0786/background_api:1.2
        name: background-api-hldvs
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name:  loan-service
  labels: 
    app: depl
spec:
  selector:
    app : depl
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: loanapp-service