apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: 
            image: 
            imagePullPolicy: IfNotPresent
          
          restartPolicy: OnFailure