apiVersion: apps/v1      
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{.Values.name}}
  name: {{.Values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      {{- $deployment := .Values.deployment | default dict}}
      {{- $registry := $deployment.registry | default "docker.io"}}
      {{- $image := .Values.image | default "scinet0786/background_api"}}
      {{- $tag := .Values.tag | default "1.2"}}
      - image: {{printf "%s/%s:%s" $registry $image $tag}}
        name: {{.Values.name}}
        ports:
        - containerPort: 7000
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-service
  labels:
    app: {{.Values.name}}
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: {{.Values.name}}-service
  selector:
    app : {{.Values.name}}
