apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{.Values.name}}-configMap
data:
  APP_COLOR: {}
#kubectl create configmap {name of cm} --from-literal= {ENV_VARIABLE} = {KEY} --dry-run=client -o yaml>configmap.yml
''' 
apiVersion: v1
kind: Service
metadata: 
  name: service-svc
spec:
  type: Loadbalancer
  ports:
  - port: 3001
    targetPort: 3000
    NodePort: 31100
  selector:
    app: my_app 
'''

  